version: '3'
services:
  app:
    container_name: learndocker
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    links: 
      - database
    volumes:
      - .:/usr/src/app
      
  database:
    container_name: learndocker-database
    image: mongo
    volumes:
      - ./db:/data/db
    logging: 
      driver: none
    ports:
      - "27017:27017"
    
